# Generated by Django 5.0.3 on 2024-04-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pdf_to_word_pdf_file_alter_pdf_to_word_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_to_word',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
